name: Build
on:
    push:
        branches: 
            - "main"
            - "dev"
        paths:
            - "!README.md"
            - "!biome.json"
            - "!*.d.ts"

jobs:
    build:
        name: Build and release
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Checkout builds
            uses: actions/checkout@v4
            with:
                repository: "PalmDevs/revenge-plugins-builds"
                path: "builds"
                token: ${{ secrets.BUILDS_PUSH_TOKEN }}
                ref: ${{ github.ref }}

          - name: Set env
            id: env
            run: |
                echo "hash=$GITHUB_SHA" >> "$GITHUB_OUTPUT"

          - uses: oven-sh/setup-bun@v2
            with:
              bun-version: latest

          - name: Install dependencies
            run: bun install --frozen-lockfile

          - name: Build
            run: bun run build
                
          - name: Push build
            run: |
                rm $GITHUB_WORKSPACE/builds/* || true
                cp -r dist/* $GITHUB_WORKSPACE/builds || true
                cd $GITHUB_WORKSPACE/builds
                git config --local user.email "actions@github.com"
                git config --local user.name "GitHub Actions"
                git add .
                git commit -m "Build $GITHUB_SHA" || exit 0
                git push
            env:
              GITHUB_TOKEN: ${{ secrets.BUILDS_PUSH_TOKEN }}